# Generated by Django 4.0.5 on 2022-07-23 20:22

import app_articles.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ім`я')),
                ('surname', models.CharField(max_length=50, verbose_name='Призвіще')),
                ('biography', models.TextField(blank=True, verbose_name='Біографія')),
                ('img', models.FileField(default=None, upload_to='author_images/%Y/%m/%d/', validators=[app_articles.validators.validate_file_extension], verbose_name='Фото автора')),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Створювач')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автори',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Оцінка')),
                ('img', models.FileField(blank=True, default='![](../static/img/book_default.png)', null=True, upload_to='books_images/%Y/%m/%d/', verbose_name='Картинка')),
                ('img_name', models.CharField(blank=True, default=' ', max_length=20, null=True, verbose_name='Нзва картинки')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('book_author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_books.authors', verbose_name='Автор')),
                ('creator', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Додав книжку')),
            ],
            options={
                'verbose_name': 'Книжка',
                'verbose_name_plural': 'Книжки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('img', models.FileField(default=None, upload_to='genres_images/%Y/%m/%d/', validators=[app_articles.validators.validate_file_extension], verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанри',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Основна частина')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_review', to='app_books.books', verbose_name='Пов`язана книжка')),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецензії')),
            ],
            options={
                'verbose_name': 'Рецензія',
                'verbose_name_plural': 'Рецензії',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CommentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000, verbose_name='Коментар до рецензії')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор коментаря до рецензії')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_books.reviews', verbose_name='Рецензія')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_books.genres', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='books',
            name='read_books',
            field=models.ManyToManyField(blank=True, related_name='read_books', to=settings.AUTH_USER_MODEL, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='books',
            name='read_now',
            field=models.ManyToManyField(blank=True, related_name='read_now', to=settings.AUTH_USER_MODEL, verbose_name='Читаю зараз'),
        ),
        migrations.AddField(
            model_name='books',
            name='want_to_read',
            field=models.ManyToManyField(blank=True, related_name='want_to_read', to=settings.AUTH_USER_MODEL, verbose_name='Хочу прочитати'),
        ),
    ]
