# Generated by Django 4.0.5 on 2022-07-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
    ]
