# Generated by Django 4.0.5 on 2022-07-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0002_alter_genres_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img_name',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Нзва картинки'),
        ),
        migrations.AlterField(
            model_name='books',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Оцінка'),
        ),
    ]
