# Generated by Django 4.0.5 on 2022-07-23 20:22

import app_articles.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('img', models.FileField(default=None, upload_to='category_images/%Y/%m/%d/', validators=[app_articles.validators.validate_file_extension], verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.TextField(verbose_name='welcome_text')),
                ('help_text', models.TextField(verbose_name='Допомога')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Головна сторінка',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('quote', models.TextField(default='', verbose_name='Цитата')),
                ('biography', models.TextField(default='', verbose_name='Біографія')),
                ('full_name', models.CharField(default='', max_length=50, verbose_name='Повне ім`я')),
                ('related_books', models.CharField(default='', max_length=50, verbose_name='Назва')),
                ('img', models.FileField(default=None, upload_to='articles_images/%Y/%m/%d/', validators=[app_articles.validators.validate_file_extension], verbose_name='Картинка')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0, verbose_name='к-сть переглядів')),
                ('author_article', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор статті')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_articles.categories', verbose_name='Категорія')),
                ('connected_book', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book', to='app_books.books', verbose_name='Пов`язана книжка')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-id'],
            },
        ),
    ]
