# Generated by Django 4.0.5 on 2022-07-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='quote',
            field=models.TextField(blank=True, default='', verbose_name='Цитата'),
        ),
    ]
